GET https://musicbrainz.org/ws/2/release?query=barcode:%<BARCODE_FILL>%22&fmt=json&limit=1
Accept: application/json

###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/Alex
Accept: application/json

###

GET http://127.0.0.1:8000/items
Accept: application/json

